// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Designer.iOS.Storyboards
{
    public partial class OrderSuccessMsgViewController : UIViewController
    {
        public OrderSuccessMsgViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();


        }
    }
}
