// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Designer.iOS.Storyboards
{
    public partial class ProductDetailViewController : UIViewController
    {
        public ProductDetailViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            UITapGestureRecognizer profileImageTapGesture = new UITapGestureRecognizer(FavouriteImageCliked);

            favouriteImgv.AddGestureRecognizer(profileImageTapGesture);
        }

        // HEART IMAGE CLIKED ACTION
        void FavouriteImageCliked()
        {
            if ()
        }
    }
}
