// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Diagnostics;
using CoreGraphics;
using Designer.iOS.Common;
using Designer.iOS.Sources;
using Designer.iOS.Xibs;
using UIKit;

namespace Designer.iOS.Storyboards
{
    public interface IProductsViewController
    {
        void OnIndicidualProductCliked(int index);
    }

    public partial class ProductsViewController : BaseViewController, IProductsViewController
    {
        public ProductsViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // PRODUCT COLLECTION VIEW CELL REGISTERATION
            productCollectionView.RegisterNibForCell(ProductCollectionViewCell.Nib, CellIDS.PRODUCT_CELL);
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            Initialize();
        }

        // Startup Method
        public void Initialize()
        {
            try
            {
                productCollectionView.Source = new ProductSource(this);

                //famMembersCollectionview.Delegate = new AddMemberCollectionViewLayout();

                var flowlayout = new UICollectionViewFlowLayout();

                flowlayout.ItemSize = new CGSize((productCollectionView.Frame.Width / 2), ConstantsIOS.PRODUCT_CELL_HEIGHT);

                flowlayout.MinimumInteritemSpacing = 0;

                flowlayout.MinimumLineSpacing = 0;

                flowlayout.SectionInset = UIEdgeInsets.Zero;

                //flowlayout.TargetContentOffset(new CGPoint(0, 50), new CGPoint(0, 0));

                productCollectionView.CollectionViewLayout = flowlayout;

                //familyMembersCollectionViewHeight.Constant = (ConstantsIOS.FAMILY_MEMBER_CELL_HEIGHT) + ConstantsIOS.BOTTOM_SPACING_FAMILY_MEMBERS_COLLECTION_VIEW;//(ConstantsIOS.FAMILY_MEMBER_CELL_HEIGHT * (10 / 2)) + ConstantsIOS.BOTTOM_SPACING_FAMILY_MEMBERS_COLLECTION_VIEW;
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }

        // INDIVIDUAL PRODUCT CLICKED FROM THE PRODUCT LIST
        public void OnIndicidualProductCliked(int index)
        {
            NavigateToProductDetailScreen();
        }

        // PROFILE SCREEN TO CHANGE PASSWORD SCREEN NAVIGATION
        public void NavigateToProductDetailScreen()
        {
            try
            {
                //if (profile != null)
                //{
                UIStoryboard storyboardUser = UIStoryboard.FromName(StoryboardNames.USER_STORYBOARD, null);

                ProductDetailViewController productDetailViewController = storyboardUser.InstantiateViewController(StoryboardIDS.PRODUCT_DETAIL_VIEW_CONTROLLER) as ProductDetailViewController;

                this.NavigationController.PushViewController(productDetailViewController, true);
                //}
                //else
                //{
                //    ShowMessage(Constants.PROFILE_DETAIL_NOT_AVAILABLE);
                //}
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }
    }
}
